FROM python:3.9-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    gnupg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create directory for PostgreSQL certificates and download the CockroachDB certificate
RUN mkdir -p /root/.postgresql
RUN curl -o /root/.postgresql/root.crt 'https://cockroachlabs.cloud/clusters/d1a2b2c7-9efd-4c03-a694-4afffbfe0993/cert'

# Install Playwright browsers
RUN pip install playwright && \
    python -m playwright install --with-deps chromium

# Copy requirements file
COPY requirements.txt ./

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY . .

# Expose port for API
EXPOSE 8000

# Command to run the app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]