name: Update Stream Counts

on:
  schedule:
    - cron: "0 22 * * *" # Run at 10PM UTC (5PM EST)
  workflow_dispatch: # Allow manual triggers

jobs:
  update-streams:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Create .env file
        run: |
          echo "COCKROACH_DB_USER=${{ secrets.COCKROACH_DB_USER }}" >> .env
          echo "COCKROACH_DB_PW=${{ secrets.COCKROACH_DB_PW }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}" >> .env
          echo "SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}" >> .env

      - name: Setup CockroachDB Certificate
        run: |
          mkdir -p $HOME/.postgresql/
          echo "${{ secrets.COCKROACH_CA_CERT }}" > $HOME/.postgresql/root.crt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Update stream counts
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python scripts/update_streams.py
